# This file is auto-generated by the update-formula workflow.
# Run: gh workflow run update-formula.yml -f version=<VERSION>
class Descry < Formula
  desc "Local action firewall for AI coding agents"
  homepage "https://descry.app"
  license "Apache-2.0"
  version "0.0.0"

  def install
    bin.install "descry"
  end
end
